# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-22 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('car_id', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.IntegerField(max_length=11, unique=True)),
                ('status', models.IntegerField(choices=[(0, '预约中'), (1, '预约成功'), (2, '预约失败')], default=0)),
            ],
            options={
                'db_table': 'By_appointments',
            },
        ),
        migrations.CreateModel(
            name='SellAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.IntegerField(max_length=11, unique=True)),
                ('status', models.IntegerField(choices=[(0, '待确认'), (1, '预约成功'), (2, '预约失败')], default=0)),
            ],
            options={
                'db_table': 'By_sell_appointments',
            },
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('like_car_id', models.IntegerField()),
            ],
            options={
                'db_table': 'By_user_likes',
            },
        ),
    ]
