# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0002_appointments_sellappointments_userlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='sellappointments',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
