# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0003_auto_20191022_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='accident',
            field=models.CharField(default='无', max_length=128),
        ),
        migrations.AddField(
            model_name='cars',
            name='commercial_insurance',
            field=models.CharField(default='已过期', max_length=128),
        ),
        migrations.AddField(
            model_name='cars',
            name='compulsory_insurance',
            field=models.CharField(default='2019-10', max_length=128),
        ),
        migrations.AddField(
            model_name='cars',
            name='emission',
            field=models.CharField(default='国Ⅳ', max_length=64),
        ),
        migrations.AddField(
            model_name='cars',
            name='license_plate',
            field=models.CharField(default='潍坊', max_length=128),
        ),
        migrations.AddField(
            model_name='cars',
            name='maintenance',
            field=models.CharField(default='定期4S保养', max_length=128),
        ),
        migrations.AddField(
            model_name='cars',
            name='purpose',
            field=models.CharField(default='家用', max_length=128),
        ),
        migrations.AddField(
            model_name='cars',
            name='yearly_check',
            field=models.CharField(default='2019-10', max_length=128),
        ),
        migrations.AlterField(
            model_name='cars',
            name='trait',
            field=models.IntegerField(choices=[(0, '新上架'), (1, '普通车'), (2, '严选车'), (3, '超值购')], default=0),
        ),
    ]
