# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0004_auto_20191023_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='transfer_fee',
            field=models.CharField(default='包含过户费', max_length=64),
        ),
    ]
