# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0005_cars_transfer_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('u_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=128)),
            ],
        ),





        migrations.RenameField(
            model_name='users',
            old_name='icon',
            new_name='wx_icon',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='wx_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='wx_phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='openid',
        ),
        migrations.AddField(
            model_name='cars',
            name='failed_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='is_check',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核未通过')], default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='u_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='u_phone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.IntegerField(choices=[(0, '待确认'), (1, '已确认'), (2, '已取消'), (3, '已失效')], default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='accident',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cars',
            name='commercial_insurance',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cars',
            name='compulsory_insurance',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cars',
            name='emission',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img1',
            field=models.ImageField(upload_to='cars/img'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='license_plate',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cars',
            name='maintenance',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cars',
            name='purpose',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cars',
            name='trait',
            field=models.IntegerField(choices=[(0, '新上架'), (1, '普通车'), (2, '严选车'), (3, '超值购'), (4, '已下架'), (5, '已售')], default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transfer_fee',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cars',
            name='yearly_check',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sellappointments',
            name='status',
            field=models.IntegerField(choices=[(0, '待确认'), (1, '已确认'), (2, '已取消'), (3, '已失效')], default=0),
        ),

        migrations.AddField(
            model_name='shops',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bo_yuan.Users'),
        ),
    ]
