# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0006_auto_20191023_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue_cars',
            name='car_serie',
        ),
        migrations.RemoveField(
            model_name='issue_cars',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='issue_cars',
            name='issue_user',
        ),
        migrations.RemoveField(
            model_name='sellcars',
            name='car_serie',
        ),
        migrations.RemoveField(
            model_name='sellcars',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='sellcars',
            name='sell_user',
        ),

        migrations.DeleteModel(
            name='Issue_Cars',
        ),
        migrations.DeleteModel(
            name='SellCars',
        ),
    ]
