# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-23 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0007_auto_20191023_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='commercial_insurance',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='compulsory_insurance',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='yearly_check',
        ),
    ]
