# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0008_auto_20191023_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='commercial_insurance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='compulsory_insurance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='yearly_check',
            field=models.DateField(null=True),
        ),
    ]
