# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-23 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0009_auto_20191023_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='commercial_insurance',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='compulsory_insurance',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='yearly_check',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
