# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0010_auto_20191023_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='uid',
        ),
        migrations.AddField(
            model_name='users',
            name='contacts',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
    ]
