# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0011_auto_20191024_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
