# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0013_appointments_u_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='u_name',
            new_name='name',
        ),
    ]
