# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0014_auto_20191024_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='cars_status',
            field=models.IntegerField(choices=[(0, '上架'), (1, '未上架')], default=0),
        ),
    ]
