# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0015_cars_cars_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='wx_phone',
            new_name='openid',
        ),
        migrations.AddField(
            model_name='sellappointments',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
