# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0016_auto_20191024_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='car_user',
            field=models.IntegerField(default=1),
        ),
    ]
