# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0018_auto_20191024_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='car_user',
            field=models.IntegerField(default=1),
        ),

        migrations.AlterField(
            model_name='sellappointments',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
