# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0019_auto_20191024_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fwb',
            name='content',
            field=models.TextField(),
        ),
    ]
