# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-25 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0021_brands_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
