# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-25 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0022_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='img',
            table='By_imgs',
        ),
    ]
