# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0023_auto_20191025_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='cars_status',
            field=models.IntegerField(choices=[(0, '上架'), (1, '未上架'), (2, '已售')], default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img2',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img3',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img4',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img5',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='trait',
            field=models.IntegerField(choices=[(0, '新上架'), (1, '普通车'), (2, '严选车'), (3, '超值购')], default=0),
        ),
    ]
