# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0024_auto_20191025_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(max_length=128),
        ),
    ]
