# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0025_auto_20191025_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='down_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='ratio',
            field=models.FloatField(default=0),
        ),
    ]
