# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-28 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0027_auto_20191028_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to='video')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'By_video',
            },
        ),
    ]
