# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0029_auto_20191028_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_img',
            field=models.CharField(default='', max_length=256),
        ),
    ]
