# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-28 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0030_video_video_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_img',
        ),
    ]
