# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0031_remove_video_video_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='video_img',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
