# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bo_yuan', '0032_cars_video_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstypes',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
